"""
TD-MPC-style planning for MPC
==============================

`phase2.py` implements two MPC inner loops -- CEM and MPPI -- both operating on
a *fixed* known model with no terminal value and no policy involved in the
sampling. This module keeps everything else about the MPC loop (replan every
step, warm start, known deterministic model rollout via the env's batched
helpers) and swaps in the planning method from:

    Hansen, Wang & Su, "Temporal Difference Learning for Model Predictive
    Control", arXiv:2203.04955 (TD-MPC), Algorithm 1 (planning / inference).

TD-MPC's planner differs from `phase2.py`'s plain MPPI in three ways, all
implemented here:

  1. **Terminal value.** Each candidate trajectory's H-step return is extended
     with a value estimate at the horizon: J = sum_h gamma^h r_h + gamma^H
     V(s_H). TD-MPC learns this V via TD-learning; here (matching this repo's
     known-model setting and Phase III of the assignment) V can be the
     *analytical* optimal LQR value `-s^T P s` (`optimal.LQRController.value`).
  2. **Policy-guided candidates.** In addition to sampling from the Gaussian
     N(mu, sigma^2), a small extra batch of trajectories is generated by
     rolling a learned policy prior (the trained SAC actor, `sac_lqr.pt`)
     through the known deterministic model. Both batches compete together in
     the same elite selection -- the policy is not just used to *seed* the
     Gaussian (contrast with `policy_prior_CEM.py`), it stays "in the loop"
     every iteration.
  3. **Elite trimming before the soft update.** Plain MPPI (`phase2.py`'s
     `MPPIPlanner`) reward-weights *all* N samples. TD-MPC first keeps only
     the top-K elites (as CEM does) and only then computes softmax weights
     over those elites to update (mu, sigma) -- a hybrid of CEM's hard
     truncation and MPPI's soft averaging.

NB: TD-MPC's original planner floors the refit sigma at a minimum ``min_sigma``
(their epsilon) so the sampler can never fully stop exploring -- a fix for the
premature-convergence failure mode this repo diagnosed empirically in
`pureCEM.py` / `Experimental Report2_Policy Prior.md`. That floor has been
REMOVED here on purpose: sigma is left free to collapse so premature
convergence can occur and be measured.

Everything else -- warm start by shifting the converged mean forward one step,
`.act(state)` / `run_episode()` -- matches `phase2.py`'s conventions.
"""

from __future__ import annotations

from typing import TYPE_CHECKING, Callable

import numpy as np

from lqr_env import LQREnv

# torch (and the SAC prior it backs) is only needed for the policy-guided
# candidate path. Import it lazily so the value-free / no-prior planner runs in
# environments without the deep-RL stack installed.
if TYPE_CHECKING:
    from policy_prior_CEM import SACPrior


# --------------------------------------------------------------------------- #
# shared trajectory evaluation (same as phase2.py, plus an optional terminal
# value term -- the sum-of-rewards-plus-value-at-horizon objective in
# TD-MPC's Algorithm 1: phi_Gamma = sum_h gamma^h R + gamma^H Q(z_H, a_H)).
# --------------------------------------------------------------------------- #
def _rollout_returns(
    env: LQREnv,
    state: np.ndarray,
    actions: np.ndarray,
    gamma: float,
    terminal_value: Callable[[np.ndarray], np.ndarray] | None = None,
) -> np.ndarray:
    """Discounted H-step return of each sequence in ``actions`` (N, H, adim),
    optionally plus a terminal value ``terminal_value(states) -> (N,)`` at the
    horizon."""
    N = actions.shape[0]
    H = actions.shape[1]
    states = np.tile(np.asarray(state, dtype=np.float64), (N, 1))   # (N, n)
    returns = np.zeros(N)
    discount = 1.0
    for h in range(H):
        a = actions[:, h, :]
        returns += discount * env.reward_batch(states, a)
        states = env.dynamics_batch(states, a)
        discount *= gamma
    if terminal_value is not None:
        returns += discount * terminal_value(states)
    return returns


# --------------------------------------------------------------------------- #
# policy-guided candidate trajectories
# --------------------------------------------------------------------------- #
def _policy_rollout_batch(prior: "SACPrior", env: LQREnv, state: np.ndarray, H: int, n: int) -> np.ndarray:
    """Sample ``n`` stochastic H-step action sequences from the policy prior,
    rolled through the known deterministic model.

    Mirrors TD-MPC's "sample N_pi trajectories using policy pi_theta": at each
    step, draw an action from the policy's actual (squashed-Gaussian) action
    distribution -- not just its mean -- then advance the model with that
    sampled action, so the resulting states along the rollout reflect the
    policy's own stochasticity just as they would if pi_theta were executed
    open-loop.

    torch is imported here (not at module load) so the rest of the planner
    stays importable without the deep-RL stack.
    """
    import torch

    adim = env.action_dim
    actions = np.zeros((n, H, adim))
    states = np.tile(np.asarray(state, dtype=np.float64), (n, 1))
    with torch.no_grad():
        for h in range(H):
            s_t = torch.as_tensor(states, dtype=torch.float32)
            a_t, _, _ = prior.actor.sample(s_t)
            a = a_t.numpy().astype(np.float64)
            actions[:, h, :] = a
            states = env.dynamics_batch(states, a)
    return actions


# --------------------------------------------------------------------------- #
# TD-MPC planner
# --------------------------------------------------------------------------- #
class TDMPCPlanner:
    def __init__(
        self,
        env: LQREnv,
        horizon: int = 5,
        num_samples: int = 512,
        num_policy_samples: int = 25,
        num_elites: int = 64,
        max_iters: int = int(1e3),
        sigma_init: float = 2.0,
        temperature: float = 20.0,
        tol_mu: float = 1e-3,
        tol_sigma: float = 1e-3,
        gamma: float = 1.0,
        terminal_value: Callable[[np.ndarray], np.ndarray] | None = None,
        prior: "SACPrior | None" = None,
        seed: int | None = None,
    ):
        """
        Parameters
        ----------
        horizon             : planning horizon H (TD-MPC default: 5).
        num_samples         : Gaussian-sampled sequences per iteration (N).
        num_policy_samples  : extra sequences rolled out from ``prior`` per
                               iteration (N_pi). 0 / ``prior=None`` -> plain
                               MPPI-with-elites (no policy candidates).
        num_elites          : top-K trajectories kept before the soft update.
        max_iters           : hard cap on refinement iterations per timestep;
                               with the default 1e10 the loop runs until it
                               converges via tol_mu / tol_sigma (TD-MPC's paper
                               uses a fixed 6).
        sigma_init          : std the Gaussian is (re)initialized to.
        tol_mu              : stop when ||mu - prev_mu|| < tol_mu.
        tol_sigma           : stop when max(sigma) < tol_sigma (collapsed).
        temperature         : softmax denominator lambda over elite returns
                               (small -> greedy), same convention as
                               `phase2.MPPIPlanner`.
        gamma               : discount for the planned return.
        terminal_value      : optional vectorized V(states) -> (N,) added
                               after H steps (e.g. `optimal.LQRController.value`
                               batched, or ``None`` for pure finite-horizon).
        prior               : a preloaded `policy_prior_CEM.SACPrior` used to
                               generate policy-guided candidates every
                               iteration. ``None`` disables this feature.
        """
        self.env = env
        self.horizon = int(horizon)
        self.num_samples = int(num_samples)
        self.num_policy_samples = int(num_policy_samples) if prior is not None else 0
        self.num_elites = int(num_elites)
        self.max_iters = int(max_iters)
        self.sigma_init = float(sigma_init)
        self.temperature = float(temperature)
        self.tol_mu = float(tol_mu)
        self.tol_sigma = float(tol_sigma)
        self.gamma = float(gamma)
        self.terminal_value = terminal_value
        self.prior = prior
        self.rng = np.random.default_rng(seed)
        self.reset()

    def reset(self) -> None:
        """Clear the warm-started mean (call between episodes)."""
        self.mu = np.zeros((self.horizon, self.env.action_dim))
        # premature-convergence bookkeeping (per episode)
        self.n_plans = 0
        self.n_premature = 0

    def _check_premature(self, state: np.ndarray, mu: np.ndarray, sigma: np.ndarray) -> bool:
        """Probe whether the converged plan ``mu`` is only a *premature* optimum:
        perturb each action coordinate by +/-10 sigma and see if any single such
        move improves the planned return. If so, the sampler collapsed before
        reaching a real optimum (the distribution stopped exploring too early).

        Uses the SAME objective the planner optimizes -- H-step return PLUS the
        terminal value -- so the check is consistent with what convergence meant
        (this is why ``self.terminal_value`` is passed, unlike the plain-CEM
        variants whose objective has no terminal term)."""
        lo, hi = self.env.action_low, self.env.action_high
        mu_return = _rollout_returns(self.env, state, mu[None], self.gamma, self.terminal_value)[0]
        H, adim = mu.shape
        for h in range(H):
            for d in range(adim):
                for sign in (1.0, -1.0):
                    mu_test = mu.copy()
                    mu_test[h, d] += sign * 10.0 * sigma[h, d]
                    test_return = _rollout_returns(
                        self.env, state, np.clip(mu_test, lo, hi)[None], self.gamma,
                        self.terminal_value,
                    )[0]
                    if test_return > mu_return:
                        return True
        return False

    def plan(self, state: np.ndarray) -> np.ndarray:
        H, N, Npi, K = self.horizon, self.num_samples, self.num_policy_samples, self.num_elites
        adim = self.env.action_dim
        lo, hi = self.env.action_low, self.env.action_high
        lam = self.temperature

        mu = self.mu                                  # warm-started mean
        sigma = np.full((H, adim), self.sigma_init)    # reset exploration

        # policy-guided candidates: rolled out once per timestep (not
        # re-sampled every refinement iteration -- TD-MPC's own implementation
        # draws these once per planning call and reuses them across
        # iterations, competing against the freshly-resampled Gaussian batch).
        if Npi > 0:
            policy_actions = _policy_rollout_batch(self.prior, self.env, state, H, Npi)
        else:
            policy_actions = np.zeros((0, H, adim))

        converged = False
        for _ in range(self.max_iters):
            prev_mu = mu

            # 1. sample N sequences from the current Gaussian + clip
            noise = self.rng.normal(size=(N, H, adim))
            gauss_actions = np.clip(mu + sigma * noise, lo, hi)
            actions = np.concatenate([gauss_actions, policy_actions], axis=0) if Npi else gauss_actions

            # 2. evaluate: H-step discounted reward + terminal value
            returns = _rollout_returns(self.env, state, actions, self.gamma, self.terminal_value)

            # 3. top-K elites (hard truncation, as in CEM)
            elite_idx = np.argpartition(returns, -K)[-K:]
            elite_actions = actions[elite_idx]
            elite_returns = returns[elite_idx]

            # 4. importance-weighted (soft, MPPI-style) update over the
            #    elites only. NOTE: the sigma floor (min_sigma) has been
            #    removed -- sigma is free to collapse, so premature
            #    convergence can occur and be measured.
            beta = elite_returns.max()
            weights = np.exp((elite_returns - beta) / lam)
            weights /= weights.sum()

            mu = np.einsum("n,nhd->hd", weights, elite_actions)
            var = np.einsum("n,nhd->hd", weights, (elite_actions - mu) ** 2)
            sigma = np.sqrt(var)

            # convergence
            if np.linalg.norm(mu - prev_mu) < self.tol_mu or sigma.max() < self.tol_sigma:
                converged = True
                break

        # record whether this planning call converged prematurely
        self.n_plans += 1
        if converged and self._check_premature(state, mu, sigma):
            self.n_premature += 1

        action = mu[0].copy()
        # warm start: shift the plan forward by one step
        self.mu = np.vstack([mu[1:], np.zeros((1, adim))])
        return action

    def act(self, state: np.ndarray) -> np.ndarray:
        return self.plan(state)


# --------------------------------------------------------------------------- #
# rollout
# --------------------------------------------------------------------------- #
def run_episode(env: LQREnv, agent: TDMPCPlanner, init_state=None, T: int | None = None):
    """Roll out the (warm-started) planner; return (total_reward, state_trajectory)."""
    if hasattr(agent, "reset"):
        agent.reset()
    s = env.reset(state=init_state)
    if T is None:
        T = env.max_steps
    total = 0.0
    traj = [s.copy()]
    for _ in range(T):
        a = agent.act(s)
        s, r, term, trunc, _ = env.step(a)
        total += r
        traj.append(s.copy())
        if term or trunc:
            break
    return total, np.array(traj)


if __name__ == "__main__":
    from optimal import LQRController, run_episode as run_optimal_episode

    env = LQREnv(noise_std=0.0, seed=0)
    s0 = np.array([1.0, -1.0, 0.5])

    ctrl = LQRController(env)
    opt_r, _ = run_optimal_episode(LQREnv(noise_std=0.0, seed=0), ctrl, init_state=s0, T=200)
    print(f"Optimal LQR                             reward (T=200): {opt_r:.4f}")

    # analytical terminal value V(s) = -s^T P s (Phase III's terminal value)
    def terminal_value(states: np.ndarray) -> np.ndarray:
        return -np.einsum("ni,ij,nj->n", states, ctrl.P, states)

    # optional policy prior for policy-guided candidates (torch-backed)
    import os
    prior = None
    if os.path.exists("sac_lqr.pt"):
        from policy_prior_CEM import SACPrior
        prior = SACPrior("sac_lqr.pt")
    else:
        print("sac_lqr.pt not found -> running without policy-guided candidates.")

    for H in (5, 15):
        env = LQREnv(noise_std=0.0, seed=0)
        planner = TDMPCPlanner(
            env, horizon=H, num_samples=512, num_policy_samples=25, num_elites=64,
            terminal_value=terminal_value, prior=prior, seed=0,
        )
        total, traj = run_episode(env, planner, init_state=s0, T=200)
        print(f"TD-MPC planner (H={H:>2}, N=512, Npi=25, K=64) reward (T=200): "
              f"{total:.4f}   final state: {np.round(traj[-1], 5)}")
